### ISSUE TITLE
Ideas for how to version schemas

### ISSUE THREAD

**Issue by geramirez** [opencontrol/schemas#1]
I'll try to put tother some schemas and examples for version 1 and 2 for now. 

Any thoughts on how to version schemas?

**Comment by mzia** [comment]
Have you looked at this? http://www.kuwata-lab.com/kwalify/ | http://www.kuwata-lab.com/kwalify/ruby/users-guide.01.html#schema

python implementation : https://github.com/Grokzen/pykwalify

**Comment by mzia** [comment]
After digging around a bit, I am not answering your question... 

So the version could be part of the yaml schema name: schema02.yml
or we use Git tags from this repo 
or we could include a yaml canonical [tag](http://www.yaml.org/spec/1.2/spec.html#id2761292) values within the schema?

**Comment by geramirez** [comment]
After changing the schema, I was able to easily create kwalify and json-schema files.

**Comment by afeld** [comment]
We now have `schema_version` in the YAML, though this isn't reflected in the README. Is that what you mean? Or are you thinking we should define our versioning structure (i.e. whether we use [semver](http://semver.org/) or whatever)?

**Comment by mzia** [comment]
yes, `schema_version` was implemented based on this discussion.   Gabe probably missed updating the docs though.  We should prob. close this issue.

**Comment by afeld** [comment]
In terms of the versioning strategy, I do think we should say something about what constitutes a version bump, i.e.

> ## Major version bump
> - New required field/attribute added
> - Structure of a field/attribute changes
> 
> ## Minor version bump
> - Non-required attribute/field added
> - Attribute/field deprecated

**Comment by geramirez** [comment]
Yeah... this started a a way to codifying the schema outside of the compliance-masonry project, but I didn't really maintain the last couple weeks. I think that the repo could be restructured to serve as a more productive resource and maybe also contain additional validation files.

**Comment by afeld** [comment]
## Acceptance criteria

(better late than never)
- [ ] As a maintainer of Masonry, I know how the schema version should be affected for any given change.
