### ISSUE TITLE
decide on canonical schema validation file

### ISSUE THREAD

**Issue by afeld** [opencontrol/schemas#19]
Right now, this repository contains files for Kwalify and JSON Schema, which adds maintenance burden—it's easy for them to get out of sync. We should pick one and drop the other, or make a way to generate one from the other. Relevant:

http://rx.codesimply.com/faq.html#why-not-use

/cc @jcscottiii @joshuamckenty @geramirez

**Comment by geramirez** [comment]
Read the article kwalify seems like the right choice for yaml.
