### ISSUE TITLE
control_origin needs to allow for multiple values

### ISSUE THREAD

**Issue by jbarnicle** [opencontrol/schemas#26]
For some implementations (i.e. FedRamp), the control origination can contain multiple values.

**Comment by afeld** [comment]
Broken out from https://github.com/18F/cg-atlas/issues/91#issuecomment-229723857.

**Comment by pburkholder** [comment]
Since `control_origin` is only about a month old, should we add `control_origins` as a `seq` and deprecate use of `control_origin` `string` as soon as feasible?

**Comment by afeld** [comment]
Sounds good to me! I'd advocate for the same approach here as https://github.com/opencontrol/schemas/issues/25.
