### ISSUE TITLE
references/type seems to have no use

### ISSUE THREAD

**Issue by pburkholder** [opencontrol/schemas#28]
https://github.com/opencontrol/schemas/blob/master/opencontrol-component-kwalify-schema.yaml#L26-L28 has reference/type listed as required but it doesn't seem to be consumed in any useful way by masonry.

It seems to expect URL or Image as value, but those values don't seem to have any effect.

Could someone provide documentation on it's use?  Could we remove the required flag if isn't actually required?

**Comment by afeld** [comment]
As I remember, the idea was that we could have links rendered one way, but image/badge URLs actually embedded inline. I'm fine with it not being `required` though.

**Comment by afeld** [comment]
Possible that functionality go lost in the rewrite from Python to Go, or maybe it was just aspirational.

**Comment by geramirez** [comment]
> Possible that functionality go lost in the rewrite from Python to Go, or maybe it was just aspirational.

We removed the functionally in Masonry in favor of only using URLs. We figured if people really need this feature we could bring it back.

**Comment by pburkholder** [comment]
Closed by dint of #41

**Comment by afeld** [comment]
Mind keeping the issues open until the change is actually merged? Helps us keep track of things in ZenHub.

**Comment by jcscottiii** [comment]
I agree, we need more documentation on the fields. If it's holding up some type of tests, I wouldn't be opposed to removing `required`. To keep compatibility, we need to keep the field.
