### ISSUE TITLE
As a user,  I would like to see an example `opencontrol.yaml` file

### ISSUE THREAD

**Issue by pburkholder** [opencontrol/schemas#30]
We don't seem to document the top-level `opencontrol.yaml` file itself. 

I'd propose pulling in the test YAML from https://github.com/opencontrol/compliance-masonry/blob/master/config/versions/1.0.0/schema_test.go#L27-L50 and saving that here as `opencontrol-v1_0_0-example.yaml`.

**Comment by afeld** [comment]
> I would like to see an example `opencontrol.yaml` file

See https://github.com/opencontrol/compliance-masonry/issues/191 and https://github.com/opencontrol/schemas/issues/29.

> We don't seem to document the top-level `opencontrol.yaml` file itself.

It's currently documented in https://github.com/opencontrol/compliance-masonry#creating-an-opencontrol-project, but agreed that we should decide on one place or another.
