### ISSUE TITLE
Trying to make a schema for specifications

### ISSUE THREAD

**Issue by jmacarthur** [opencontrol/schemas#52]
I thought I'd try making a schema for standards files (e.g. https://github.com/opencontrol/NIST-800-53-Standards/blob/master/NIST-800-53.yaml)

However, it doesn't seem possible to specify a schema that accepts it; kwalify says that that file is neither a sequence nor a mapping. Upstream activity on Kwalify seems to have stopped. Has anyone tried making this schema before? I realise it's a trivial format and doesn't really need a schema; I'm just doing this an introductory exercise.

**Comment by jcscottiii** [comment]
@jmacarthur no one has tried to make one before. Do you have your kwalify schema file?
For Standards, it should be a mapping and should start something like this (i think):

```
type: map
mapping:
```

**Comment by jmacarthur** [comment]
I think there's several problems here. First, Kwalify doesn't like mapping key names with spaces or brackets in them, such as "AC-17 (2)" - unless you put the double quotes into the file. It does appear to be valid yaml on every implementation I've found though; I think Kwalify is being too strict.

My schema now looks like this: http://paste.baserock.org/atihajosim - but I think making a Kwalify schema would be impossible because the schema needs to contain the names of all mapping keys, and the names of the controls are mapping keys here.

**Comment by jmacarthur** [comment]
I've found the Kwalify defualt mapping rule, so you can make a valid schema: http://paste.baserock.org/dujotizici. The problem of spaces in key names still exists though; I'll try and find a way to fix that before submitting this schema.

**Comment by afeld** [comment]
> Kwalify doesn't like mapping key names with spaces or brackets in them, such as "AC-17 (2)" - unless you put the double quotes into the file

Is that a Kwalify thing, or a YAML thing?

http://yaml.org/spec/1.2/spec.html#id2787420

Happy to add double-quotes to

https://github.com/opencontrol/NIST-800-53-Standards/blob/master/NIST-800-53.yaml

if that would make it valid(atable).

**Comment by jmacarthur** [comment]
I spent a while reading the YAML 1.2 spec yesterday and couldn't figure out whether whitespace inside keys is allowed; the best I could find was "a plain scalar must not be empty, or contain leading or trailing white space characters" which suggests that whitespace is otherwise OK. Python's yaml library and all the validators I could find online accept spaces in keys though.

**Comment by afeld** [comment]
If it works with us adding double quotes to those keys, not a big deal!
