### ISSUE TITLE
create a Kwalify file for standards

### ISSUE THREAD

**Issue by afeld** [opencontrol/schemas#54]
Broken out from https://github.com/opencontrol/schemas/issues/52.

https://github.com/opencontrol/schemas#standards

/cc @jmacarthur https://github.com/opencontrol/schemas/issues/53

**Comment by anweiss** [comment]
This should include an additional field at the root for "revision" (e.g. Revision 4 for NIST 800-53)

**Comment by afeld** [comment]
@anweiss That's another place where I would worry about the schema getting too NIST-specific...I think we can just consider R5 a totally separate standard from R4, even if they end up living in the same repository. Thoughts?

**Comment by anweiss** [comment]
Hmm good point. I think that's a solid approach
