### ISSUE TITLE
Consider alternative schema validator to kwalify

### ISSUE THREAD

**Issue by aegershman** [opencontrol/schemas#89]
~~In order to ensure opencontrol schema validation is flexible and adapted to newer tooling, consider an alternative schema validation from kwalify.~~

Not that there's anything inherently wrong with `kwalify`, but it's ~11+ years old since it's last release (https://github.com/kvs/kwalify + http://www.kuwata-lab.com/kwalify/), and there may be alternative schema descriptors and validations which are a bit more widely-used nowadays than `kwalify` (maybe*. and it doesn't mean others would be any 'easier' or 'better' anyway).

some considerations:

- openapiv3, which most folks would probably be familiar with from Kubernetes CRD resource definitions? https://openapi.tools/#data-validators unsure if there are straightforward standalone clis for validating a document against a schema document
- jsonschema (https://json-schema.org/implementations.html) which I'm familiar with from `jsonresume` (https://github.com/jsonresume/resume-schema/blob/v1.0.0/schema.json) but not sure if that's really what we want + provides happy interop with golang tooling. I just genuinely don't know, and, of course, I haven't done research on it, so I'm talking out of my butt.

---

I crossed out my initial issue comment body because I don't think this is _super_ pressing issue-- and I don't have a strong contender for an alternative, **let alone if it should be considered at all**-- but still, putting it here for issue-tracking purposes. There doesn't seem to be anything _broken_ with the current setup, so it might be just as well to leave it be.

Thanks! 👍

**Comment by redhatrises** [comment]
I definitely think if anything that some sort of validator integrated into compliance masonry itself would be the best thing. https://pkg.go.dev/github.com/go-openapi/validate?tab=doc might be the best thing.

**Comment by redhatrises** [comment]
https://github.com/opencontrol/compliance-masonry/tree/master/pkg/cli/validate might also provide what you are looking for.... might not... haven't really looked at it.

**Comment by jenglish** [comment]
There is a json-schema translation of the OpenControl schemas available here:

https://github.com/jenglish/ssptool/blob/master/lib/opencontrol/schemas.js

Notes: this is json-schema embedded in JavaScript, not strictly json-schema, and there are some additional, ssptool-specific schemata in that file.

I was pretty happy with the available tooling for nodejs, as well as the json-schema notation itself.

**Comment by fgm** [comment]
@aegershman any reason you could share on why you eventually decided to close the issue ?

**Comment by aegershman** [comment]
@fgm Eh, it was an old issue and I just wanted to keep my personal number of open issues down, that's the only reason. Plus, at the time, I didn't have the ability to actually implement the changes myself. So I went ahead and just closed it out 👍
